### ISSUE TITLE
那个网站无法评论？

### ISSUE THREAD

**Issue by pwxc** [pwxcoo/pwxcoo.github.io#1]
事情是这样子，
我今天早上刚刚起床，
看到你的项目有新的动作，
我就点开看看，
我看到了一个网址，
访问进去是一个博客。
我觉得很有意思，就哈哈大笑了出来。但是我发现我没有办法让你知道
我觉得这是一个缺陷，没有评论的博客也能叫博客吗？ @pwxcoo

**Comment by pwxcoo** [comment]
事情是这样的，我觉得一个博客要是让人随便评论的话，倘若境外反华势力在我这个博客下评论反华言论，势必会造成极其恶劣的影响，所以我关闭了评论，杜绝了违法的行为。十九大都开了，你还在卖糖水嘛。
